version: "3"

services:

   # 1st mobile number
  firefox_994704414285:
    image: selenium/standalone-firefox-debug:3.141.59-dubnium
    ports:
      - "4441:4444"
      - "5901:5900"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - selenium
    restart: on-failure

  whatsapp_994704414285:
     build: .
     environment:
       - SELENIUM=http://firefox_994704414285:4444/wd/hub
       - MOBILE_NUMBER=994704414285
     volumes:
       - ".:/app"
     command: /app/docker-entrypoint.sh
     networks:
       - selenium
     depends_on:
       - firefox_994704414285
     #restart: on-failure


  # 2nd mobile number
  firefox_994704414286:
    image: selenium/standalone-firefox-debug:3.141.59-dubnium
    ports:
      - "4442:4444"
      - "5902:5900"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - selenium
    restart: on-failure

  whatsapp_994704414286:
     build: .
     environment:
       - SELENIUM=http://firefox_994704414286:4444/wd/hub
       - MOBILE_NUMBER=994704414286
     volumes:
       - ".:/app"
     command: /app/docker-entrypoint.sh
     networks:
       - selenium
     depends_on:
       - firefox_994704414286
     #restart: on-failure

  # 3rd mobile number
  firefox_994704414287:
    image: selenium/standalone-firefox-debug:3.141.59-dubnium
    ports:
      - "4443:4444"
      - "5903:5900"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - selenium
    restart: on-failure

  whatsapp_994704414287:
     build: .
     environment:
       - SELENIUM=http://firefox_994704414287:4444/wd/hub
       - MOBILE_NUMBER=994704414287
     volumes:
       - ".:/app"
     command: /app/docker-entrypoint.sh
     networks:
       - selenium
     depends_on:
       - firefox_994704414287
     #restart: on-failure


  # 4th mobile number
  firefox_994704414288:
    image: selenium/standalone-firefox-debug:3.141.59-dubnium
    ports:
      - "4444:4444"
      - "5904:5900"
    volumes:
      - "/dev/shm:/dev/shm"
    networks:
      - selenium
    restart: on-failure

  whatsapp_994704414288:
     build: .
     environment:
       - SELENIUM=http://firefox_994704414288:4444/wd/hub
       - MOBILE_NUMBER=994704414288
     volumes:
       - ".:/app"
     command: /app/docker-entrypoint.sh
     networks:
       - selenium
     depends_on:
       - firefox_994704414288
     #restart: on-failure


volumes:
  devshm:

networks:
  selenium: